name: update-data

on:
  schedule:
    # Run nightly 3am
    - cron: 0 3 * * *
  pull_request:
    branches_ignore: []

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python environment
        run: |
          conda create -c conda-forge -y -q --name env Jinja2

      - name: Update data
        run: |
          git clone https://github.com/LLNL/llnl.github.io /tmp/llnl.github.io
          conda create -c conda-forge -y -q --name env Jinja2
          rm -rf data/
          mv /tmp/llnl.github.io/explore/github-data data/

      - name: Generate updated page
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate env
          python run.py
          
    - name: Push Fixes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        printf "GitHub Actor: ${GITHUB_ACTOR}\n"
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add data/
        git add index.html
        set +e
        git status | grep modified
        if [ $? -eq 0 ]; then
            set -e
            printf "Changes\n"
            git commit -m "Automated push to update data $(date '+%Y-%m-%d')" || exit 0
            git push origin main
        else
            set -e
            printf "No changes\n"
        fi
